title: "Preet Shah"
email: shahpreetk@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  An addicted coffee and kitty lover ♥️
  Frotend Web Developer, on the path to become a Full Stack Web Developer 
baseurl: "/" 
url: "/mlh-portfolio" 
twitter_username: shahpreet25
github_username:  shahpreetk

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
